# Generated by Django 4.1.7 on 2023-05-08 18:37

from django.db import migrations, models
import django.db.models.deletion
import geodjango_test.models.address


class Migration(migrations.Migration):
    dependencies = [
        ("geodjango_test", "0003_alter_person_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="Address",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("street", models.CharField(max_length=100)),
                ("city", models.CharField(max_length=100)),
                (
                    "zipcode",
                    models.CharField(
                        max_length=6,
                        validators=[geodjango_test.models.address.zipcode_validator],
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="geodjango_test.person",
                    ),
                ),
            ],
        ),
    ]
