# Generated by Django 4.1.7 on 2023-05-08 18:43

import django.contrib.gis.db.models.fields
import django.contrib.gis.geos.point
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("geodjango_test", "0004_address"),
    ]

    operations = [
        migrations.AddField(
            model_name="address",
            name="location",
            field=django.contrib.gis.db.models.fields.PointField(
                default=django.contrib.gis.geos.point.Point(0, 0), srid=4326
            ),
        ),
    ]
